### ISSUE TITLE
屏幕可以同步，但是操作不了，看sessionid返回的都是null

### ISSUE THREAD

**Issue by 10508zhl** [openatx/atxserver2-ios-provider#12]

**Comment by 10508zhl** [comment]
最新的WDA会返回null，回退历史版本的WDA 操作了，但是延时特别特别大

**Comment by 10508zhl** [comment]
改动wda对应的代码，延时很小了

**Comment by d182231609** [comment]
> 改动wda对应的代码，延时很小了

能告诉下退回的是哪个版本吗？还有如何改动wda代码可以减少延迟

**Comment by 10508zhl** [comment]
> > 改动wda对应的代码，延时很小了
> 
> 能告诉下退回的是哪个版本吗？还有如何改动wda代码可以减少延迟

https://testerhome.com/topics/19292 这篇里面有介绍，对应改那2个函数就可以了

**Comment by d182231609** [comment]
> > > 改动wda对应的代码，延时很小了
> > 
> > 
> > 能告诉下退回的是哪个版本吗？还有如何改动wda代码可以减少延迟
> 
> https://testerhome.com/topics/19292 这篇里面有介绍，对应改那2个函数就可以了

我xcode版本是11.5的，改了对应的方法后发现XCEventGenerator在10.1以上的版本就已经移除了，无法构建，后来我替换了xcdoe10的XCTest.framework到11.5发现可以构建了。
但是运行的时候发现点击和移动的方法都无效了。

+ (id<FBResponsePayload>)handleDragCoordinate:(FBRouteRequest *)request
{
//  FBSession *session = request.session;
  CGPoint startPoint = CGPointMake((CGFloat)[request.arguments[@"fromX"] doubleValue], (CGFloat)[request.arguments[@"fromY"] doubleValue]);
  CGPoint endPoint = CGPointMake((CGFloat)[request.arguments[@"toX"] doubleValue], (CGFloat)[request.arguments[@"toY"] doubleValue]);
  NSTimeInterval duration = [request.arguments[@"duration"] doubleValue];
//  XCUICoordinate *endCoordinate = [self.class gestureCoordinateWithCoordinate:endPoint application:session.activeApplication shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
//  XCUICoordinate *startCoordinate = [self.class gestureCoordinateWithCoordinate:startPoint application:session.activeApplication shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
//  [startCoordinate pressForDuration:duration thenDragToCoordinate:endCoordinate];
  [[XCEventGenerator sharedGenerator] pressAtPoint:startPoint forDuration:duration liftAtPoint:endPoint velocity:1000 orientation:0 name:@"drag" handler:^(XCSynthesizedEventRecord *record, NSError *error) {}];
  return FBResponseWithOK();
}

我是这么改的，能帮我看下什么问题吗？

**Comment by d182231609** [comment]
> > > > 改动wda对应的代码，延时很小了
> > > 
> > > 
> > > 能告诉下退回的是哪个版本吗？还有如何改动wda代码可以减少延迟
> > 
> > 
> > https://testerhome.com/topics/19292 这篇里面有介绍，对应改那2个函数就可以了
> 
> 我xcode版本是11.5的，改了对应的方法后发现XCEventGenerator在10.1以上的版本就已经移除了，无法构建，后来我替换了xcdoe10的XCTest.framework到11.5发现可以构建了。
> 但是运行的时候发现点击和移动的方法都无效了。
> 
> * (id)handleDragCoordinate:(FBRouteRequest *)request
>   {
>   //  FBSession *session = request.session;
>   CGPoint startPoint = CGPointMake((CGFloat)[request.arguments[@"fromX"] doubleValue], (CGFloat)[request.arguments[@"fromY"] doubleValue]);
>   CGPoint endPoint = CGPointMake((CGFloat)[request.arguments[@"toX"] doubleValue], (CGFloat)[request.arguments[@"toY"] doubleValue]);
>   NSTimeInterval duration = [request.arguments[@"duration"] doubleValue];
>   //  XCUICoordinate *endCoordinate = [self.class gestureCoordinateWithCoordinate:endPoint application:session.activeApplication shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
>   //  XCUICoordinate *startCoordinate = [self.class gestureCoordinateWithCoordinate:startPoint application:session.activeApplication shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
>   //  [startCoordinate pressForDuration:duration thenDragToCoordinate:endCoordinate];
>   [[XCEventGenerator sharedGenerator] pressAtPoint:startPoint forDuration:duration liftAtPoint:endPoint velocity:1000 orientation:0 name:@"drag" handler:^(XCSynthesizedEventRecord *record, NSError *error) {}];
>   return FBResponseWithOK();
>   }
> 
> 我是这么改的，能帮我看下什么问题吗？

已经可以了，我自己的问题。谢谢

**Comment by 201905270246** [comment]
@10508zhl  @d182231609 请问你们回退到WDA的那个版本？我也遇到这个问题，回退了appium/WDA的2.0.0和v2.3.3。/status返回的sessionID 也是null

**Comment by 201905270246** [comment]
@10508zhl @d182231609 尝试换到appium/WebDriverAgent v2.9.0可以获取到sessionID

**Comment by zhujj-coder** [comment]
> 替换了xcdoe10的XCTest.framework到11.5发现可以构建了。
> 但是运行的时候发现点击和移动的方法都无效了。

x

> > > > 改动wda对应的代码，延时很小了
> > > 
> > > 
> > > 能告诉下退回的是哪个版本吗？还有如何改动wda代码可以减少延迟
> > 
> > 
> > https://testerhome.com/topics/19292 这篇里面有介绍，对应改那2个函数就可以了
> 
> 我xcode版本是11.5的，改了对应的方法后发现XCEventGenerator在10.1以上的版本就已经移除了，无法构建，后来我替换了xcdoe10的XCTest.framework到11.5发现可以构建了。
> 但是运行的时候发现点击和移动的方法都无效了。
> 
> * (id)handleDragCoordinate:(FBRouteRequest *)request
>   {
>   //  FBSession *session = request.session;
>   CGPoint startPoint = CGPointMake((CGFloat)[request.arguments[@"fromX"] doubleValue], (CGFloat)[request.arguments[@"fromY"] doubleValue]);
>   CGPoint endPoint = CGPointMake((CGFloat)[request.arguments[@"toX"] doubleValue], (CGFloat)[request.arguments[@"toY"] doubleValue]);
>   NSTimeInterval duration = [request.arguments[@"duration"] doubleValue];
>   //  XCUICoordinate *endCoordinate = [self.class gestureCoordinateWithCoordinate:endPoint application:session.activeApplication shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
>   //  XCUICoordinate *startCoordinate = [self.class gestureCoordinateWithCoordinate:startPoint application:session.activeApplication shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
>   //  [startCoordinate pressForDuration:duration thenDragToCoordinate:endCoordinate];
>   [[XCEventGenerator sharedGenerator] pressAtPoint:startPoint forDuration:duration liftAtPoint:endPoint velocity:1000 orientation:0 name:@"drag" handler:^(XCSynthesizedEventRecord *record, NSError *error) {}];
>   return FBResponseWithOK();
>   }
> 
> 我是这么改的，能帮我看下什么问题吗？

哥们不是你一人问题啊 ，我把替换后也不能点击，麻烦告知下，怎么做到能点击和滑动的吗？多谢了
