### ISSUE TITLE
请更新下README的地址https://github.com/appium/WebDriverAgent

### ISSUE THREAD

**Issue by liyinchigithub** [openatx/atxserver2-ios-provider#25]
`git clone https://github.com/appium/WebDriverAgent Appium-WebDriverAgent
cd Appium-WebDriverAgent && ./Scripts/bootstrap.sh
open WebDriverAgent.xcodeproj`

该项目地址已被官方更改了，请更新下README

`git clone https://github.com/appium/WebDriverAgent`

**Comment by chenhengjie123** [comment]
目前 readme 内容已修正，关闭。
